[package]
name = "barrel"
version = "0.2.0-alpha0"

description = "A powerful schema migration building API for Rust"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
license = "MIT/X11 OR Apache-2.0"

readme = "README.md"
repository = "https://github.com/spacekookie/barrel"
documentation = "https://docs.rs/barrel"

categories = [ "database", "web-programming", "development-tools"]
keywords = ["sql", "database", "schema", "migration"]

[features]
default = []
diesel_filled = ["tempdir", "diesel"]

[dependencies]
tempdir = { version = "0.3.4", optional = true }
diesel = { git = "https://github.com/spacekookie/diesel", branch = "feature/barrel", default_features = false, optional = true }
