[package]
name = "barrel"
version = "0.2.3-alpha.0"

description = "A powerful schema migration building API for Rust"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
license = "MIT/X11 OR Apache-2.0"

readme = "README.md"
repository = "https://github.com/spacekookie/barrel"
documentation = "https://docs.rs/barrel"

categories = [ "database", "development-tools"]
keywords = ["sql", "database", "schema", "migration"]

[features]
default = []
diesel-filled = ["tempdir", "diesel"]

# Feature flags for per-database SQL generators
sqlite3 = []
pg = []

[dependencies]
tempdir = { version = "0.3.4", optional = true }
diesel = { version = ">= 1.1, < 2.0", default_features = false, optional = true }

[[example]]
name = "pg_strings"
required-features = ["pg"]

[[example]]
name = "sqlite_strings"
required-features = ["sqlite3"]
