[package]
name = "barrel"
version = "0.1.0"

description = "A powerful schema migration building API for Rust"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
license = "MIT/X11 OR Apache-2.0"

readme = "README.md"
repository = "https://github.com/spacekookie/barrel"
documentation = "https://docs.rs/barrel"

categories = [ "database", "web-programming", "development-tools"]
keywords = ["sql", "database", "schema", "migration"]

[features]
default = ["diesel"]

[dependencies]
diesel = { version = "1.0.0", features = ["postgres"], optional = true }