[package]
name = "barrel"
description = "A powerful schema builder API for Diesel ORM"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
license = "MIT/X11 OR Apache2"

[dependencies]
diesel = "1.0.0"
dotenv = "0.9.0"