[package]
name = "barrel"
version = "0.0.1"

description = "A powerful schema builder API for Diesel ORM"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
license = "MIT/X11"

readme = "README.md"
repository = "https://github.com/spacekookie/barrel"
documentation = "https://docs.rs/barrel"

categories = [ "database", "web-programming", "development-tools"]
keywords = ["sql", "database", "schema", "migration"]

[dependencies]
