[package]
name = "barrel_diesel"
description = "A crate that makes integration into diesel really easy"
version = "0.2.0"
license = "MIT OR Apache-2.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]

[dependencies]
diesel = { version = "1.1.0", default-features = false }